on: [push]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    strategy:
      matrix:
        include:
          - viteConfigFile: vite-desktop.config.ts
            viteOutputDir: desktop/dist
            cfProjectName: skeetdeck

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Configure pnpm
        with:
          version: 8
          run_install: false

      - name: Retrieve pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: |
          pnpm install -r --prefer-offline --frozen-lockfile
          pnpm store prune

      - name: Build project
        working-directory: app
        run: |
          RAW_COMMIT=$(git rev-parse HEAD)

          export VITE_GIT_BRANCH=$(git branch --show-current)
          export VITE_GIT_COMMIT=${RAW_COMMIT:0:7}

          pnpm exec vite build -c ${{ matrix.viteConfigFile }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: ${{ matrix.cfProjectName }}
          branch: ${{ github.ref_name == 'trunk' && 'main' || github.ref_name }}
          workingDirectory: app
          directory: ${{ matrix.viteOutputDir }}
